"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "../../../packages/app/components/common/Header.web";
import { Toaster } from "burnt/web";
import { TolgeeProvider } from "app/provider/TolgeeProvider";
import { ClientOnly } from "app/components/common/ClientOnly";
import { useState, useEffect } from "react";
import { clsx } from "clsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>NativeWeather</title>
      <body
        className={clsx(
          "dark:bg-systemBackground_dark bg-secondarySystemBackground px-4",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <ClientOnly>
          <TolgeeProvider>
            <Header />
            {children}
            <Toaster position="bottom-right" />
          </TolgeeProvider>
        </ClientOnly>
      </body>
    </html>
  );
}
